### ISSUE TITLE
Undefined variable errors

### ISSUE THREAD

**Issue by jwimpy** [proimage/MC_Player#2]
I am getting the following notices when I try to implement this into my EE code:

Notice: Undefined variable: script in C:\wamp\www\sola169-2\content\plugins\pi.mc_player.php on line 473

Notice: Undefined variable: playlist in C:\wamp\www\sola169-2\content\plugins\pi.mc_player.php on line 500

Notice: Undefined variable: script_end in C:\wamp\www\sola169-2\content\plugins\pi.mc_player.php on line 557

The video I'm working with plays fine, it's just these notices are a bit annoying. Any ideas?

**Comment by proimage** [comment]
I'm pretty sure these notices are attributable to PHP5's changes in variable declarations. I've been wrestling with eliminating them without adversely affecting something else. Could you paste the {exp:mc_player} tag code you're using for me to look at?

**Comment by jwimpy** [comment]
Thanks for looking at this. My code is pretty simple.

  {exp:weblog:entries weblog="testimonials" limit="1"}
    {exp:mc_player:play file="{media_file}" width="281" height="211" image="{custom_image}" playerpath="{site_url}/js/jwplayer/player.swf"}
    <p class="red" style="font-size:18px;"><strong>{title}</strong></p>
   {/exp:weblog:entries}

Where {media_file} and {custom_image} are custom fields in my weblog.

Thanks,

Jeff

**Comment by jwimpy** [comment]
I think I just resolved the issue:

On line 159 just below the beginning of the play() function, I added a couple lines declaring these variables - 

```
function play()
{
    global $TMPL, $SESS;

             $script='';
     $script_end='';
     $playlist='';
             ...
```

So, far that has fixed it without adverse effects. Not sure if that will cause problems in other implementations beyond how I have it set up in my code?!?

**Comment by proimage** [comment]
That does indeed fix that immediate issue, however elsewhere in the code I believe (going from memory here) that I was trying to determine whether a playlist was specified or not based on if those variables existed and/or were empty.

So, if your fix works for your purposes, run with it - just be aware that it might have adverse affects if you try to make use of the playlist functionality... not that things are bug-free to begin with, but I'm sure you know what I mean. ;)
